### ISSUE TITLE
실제 revolution pi에 올라갔을 때의 상태.

### ISSUE THREAD

**Issue by kimsehwan96** [kimsehwan96/project_socketio#8]
![스크린샷 2020-07-24 오전 11 28 17](https://user-images.githubusercontent.com/59886140/88355799-c910bc00-cda0-11ea-9b27-b59e04a00000.png)

현재 한글 깨짐 현상이 있습니다.

**Comment by jungyeonPark** [comment]
해결입니다~!!!

**Comment by kimsehwan96** [comment]
해결 된 이슈

**Comment by kimsehwan96** [comment]
sudo apt-get install -y fonts-unfonts-core ibus-hangul
